#!/bin/sh

HOSTNAME=`hostname`
CMDLINE=`cat /proc/cmdline`

NAMES="net0"
PROTOS="2"
IN="testchannel_"
OUT="testchannel_"
FLAGS="net_hdr"
EXTRA_IFACES=()

process_unikernel_ifaces () {
	# SHMSTREAM protocol used by MirageOS unikernels
	PROT="0x7ade5c549b08e814"
	for x in $CMDLINE
	do
		case "$x" in
			unikernel_iface=*)
				UNIKERNEL_IFACES="${x//unikernel_iface=}"
				;;
		esac
	done

	if [ ! -z "$UNIKERNEL_IFACES" ]
	then
		IFS=',' read -ra IFACE <<< "$UNIKERNEL_IFACES"
		for i in "${IFACE[@]}";
		do
			EXTRA_IFACES+=("$i")
			NAMES="$NAMES,$i"
			IN="$IN,$i|out"
			OUT="$OUT,$i|in"
			FLAGS="$FLAGS,eth_dev"
			PROTOS="$PROTOS,$PROT"
		done
	fi
}


case $HOSTNAME in
	nic_linux)
		IN="${IN}4"
		OUT="${OUT}3"
		IP=3
		process_unikernel_ifaces
		;;
	storage_linux)
		IN="${IN}3"
		OUT="${OUT}4"
		IP=4
		;;
	*)
		# ignore unknown hosts
		exit 0
		;;
esac

MODULE_ARGS="name=$NAMES reader_protocol=$PROTOS writer_protocol=$PROTOS"
MODULE_ARGS="$MODULE_ARGS in=$IN out=$OUT flags=$FLAGS"

case "$1" in
  start)
	echo "Starting Muen virtual networking..."
	mount -t debugfs none /sys/kernel/debug \
		&& modprobe muennet $MODULE_ARGS \
		&& ifconfig net0 up \
		&& ifconfig net0 192.168.10.$IP \
		&& ip route add 192.168.10.0/24 dev net0
	for i in "${EXTRA_IFACES[@]}";
	do
		ip link set $i master br0
		ip link set dev $i up
	done
	;;
  stop)
	echo "Stopping Muen virtual networking..."
	umount /sys/kernel/debug && rmmod muennet
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
